---

baseurl: https://caldito.me/
title: Pablo Gómez-Caldito
languageCode: en-us
theme: hello-friend-ng
paginate: 10
author:
  name: Pablo Gómez-Caldito
params:
  dateform: Jan 2, 2006
  dateformShort: Jan 2
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04"
  homeSubtitle: "I love building things with software and systems." # Here you can learn about me, check my blog and find my networks" # DevOps Engineer and CSE student based in Madrid.
  # Links
  footerLeft: Powered by <a href="https://gohugo.io/" target="_blank" rel="noopener">Hugo</a>
  footerRight: Hosted on <a href="https://pages.github.com/" target="_blank" rel="noopener">GitHub Pages</a>
  portrait:
    path: /images/me.jpg
    alt: picture
    maxWidth: 200px
  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts: false
  # Enable sharing buttons, if you linke
  enableSharingButtons: true
  # Metadata mostly used in document's head
  description: My new homepage or blog
  keywords: homepage, blog
  images: [""]
  # Default theme "light" or "dark"
  defaultTheme: light
  logo:
    logoText: /home/pablo
    logoHomeLink: /
  # Social icons
  social: 
    - name: github
      url: https://github.com/caldito
    - name: linkedin
      url: https://www.linkedin.com/in/caldito
    - name: twitter
      url:  https://twitter.com/pablogcaldito
    - name: email
      url:  mailto:pablo@caldito.me
taxonomies:
  category: blog
  tag: tags
  series: series
languages:
  en:
    copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC BY-SA 4.0</a>'
    readOtherPosts: "Read other posts"
menu:
  main: []
    #- identifier: about
    #  name: About
    #  url: about/
    #- identifier: posts
    #  name: Posts
    #  url: posts/
