baseurl      = "localhost"
title        = "Pablo GÃ³mez-Caldito"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  #<img src="{{ .Site.Params.Portrait.Path }}" class="circle" alt="{{ .Site.Params.Portrait.Alt }}" style="max-width:{{ .Site.Params.Portrait.MaxWidth }}"
  #[[params.portrait]]
  #  path = "images/me.jpg"
  #  alt = "Your example logo alt text"
  #  maxWidth = "2"
  # Subtitle for home
  homeSubtitle = "DevOps Engineer and CSE student based in Madrid"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "light"

  [params.logo]
    logoText     = "/home/pablo"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/pablogcaldito"
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/caldito"
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/pablogcaldito"
  [[params.social]]
    name = "email"
    url  = "mailto:pablogcaldito@gmail.com"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"
    path = "./me.jpg"
    alt = "Your example logo alt text"

# [menu]
#   [[menu.main]]
#     identifier = "about"
#     name       = "About"
#     url        = "about/"
#   [[menu.main]]
#     identifier = "posts"
#     name       = "Posts"
#     url        = "posts/"
